Update Yocto SDK

diff --git a/layers/meta-quectel/recipes-quectel/wifi-bt-drv/files/WiFi/scripts/check_mac_addr b/layers/meta-quectel/recipes-quectel/wifi-bt-drv/files/WiFi/scripts/check_mac_addr
--- a/layers/meta-quectel/recipes-quectel/wifi-bt-drv/files/WiFi/scripts/check_mac_addr
+++ b/layers/meta-quectel/recipes-quectel/wifi-bt-drv/files/WiFi/scripts/check_mac_addr
@@ -3,28 +3,59 @@
 TARGET_FILE="/lib/firmware/wlan/wlan_mac.bin"
 SOURCE_FILE="/var/persist/wlan_mac.bin"
 OUTPUT_FILE="/etc/bluetooth/.bt_nv.bin"
+NVDATA_FILE="/var/persist/NV_data"
 
-MAC_LINE=$(grep "^Intf0MacAddress=" "$SOURCE_FILE")
-MAC=${MAC_LINE#Intf0MacAddress=}
+DEFAULT_MAC="005533225511"
 
-if [ ${#MAC} -ne 12 ]; then
-    echo "Invalid MAC address length: $MAC"
+if [ ! -f "$NVDATA_FILE" ]; then
+    echo "Error: NV_DATA file not found: $NVDATA_FILE"
     exit 1
+fi
+
+RAW_LINE=$(grep -aEo "Quec-Head-nv1-v1.*Quec-Tail-nv1-v1" "$NVDATA_FILE" | tr -d '\0\n\r ')
+
+if [ -z "$RAW_LINE" ]; then
+    echo "Invalid file format: Quec pattern not found"
+    exit 1
+fi
+
+TAIL="Quec-Tail-nv1-v1"
+if [ ${#RAW_LINE} -le 65 ]; then
+    echo "Invalid NV_DATA length: ${#RAW_LINE}"
+    exit 1
+fi
+
+MAC_START=$(( ${#RAW_LINE} - ${#TAIL} - 12 ))
+MAC=${RAW_LINE:$MAC_START:12}
+MAC=$(echo "$MAC" | tr '[:lower:]' '[:upper:]')
+
+if [[ ! "$MAC" =~ ^[0-9A-F]{12}$ ]] || [[ "$MAC" =~ ^0+$ ]]; then
+    echo "Detected empty/invalid MAC, using default $DEFAULT_MAC"
+    MAC="$DEFAULT_MAC"
 fi
 
 {
     printf "\x00\x00\x06"
-
-    printf "\\x${MAC:0:2}\\x${MAC:2:2}\\x${MAC:4:2}\\x${MAC:6:2}\\x${MAC:8:2}\\x${MAC:10:2}"
+    for i in 10 8 6 4 2 0; do
+        printf "\x${MAC:$i:2}"
+    done
 } > "$OUTPUT_FILE"
 
+echo "BT MAC ($MAC) written to $OUTPUT_FILE"
+
 if [ $? -eq 0 ]; then
-    echo "BT MAC written to $OUTPUT_FILE"
+    echo "BT MAC ($MAC) written to $OUTPUT_FILE"
 else
     echo "Failed to write BT MAC"
     exit 1
 fi
 
+killall -9 hciattach
+echo 0 > /sys/devices/platform/rfkill/bt_en
+sleep 1
+echo 1 > /sys/devices/platform/rfkill/bt_en
+sleep 1
+hciattach /dev/ttyHS1 qca -t120 3000000 flow
 
 if [ ! -f "$SOURCE_FILE" ]; then
     echo "wlan_mac.bin is not set maybe not set by fct mode"
@@ -54,3 +85,11 @@ if [ ! -f "$TARGET_FILE" ] || ! cmp -s <(md5sum "$TARGET_FILE" | cut -d ' ' -f 1
 else
     echo "Mac.bin is not change"
 fi
+
+echo "reload wlan driver"
+rmmod wlan
+sleep 1
+insmod /lib/modules/6.6.52-qli-1.3-ver.1.1/updates/wlan.ko
+sleep 1
+ifconfig wlan0 up
+echo "reload wlan driver success"
